"""empty message

Revision ID: e7289970a79c
Revises: ed3704ce8630
Create Date: 2020-11-20 06:19:57.213307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7289970a79c'
down_revision = 'ed3704ce8630'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('one_show_byArtist_atATime', 'show', ['artist_id', 'start_time'])
    op.create_unique_constraint('one_show_perVenue_atATime', 'show', ['venue_id', 'start_time'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'show', type_='unique')
    op.drop_constraint(None, 'show', type_='unique')
    # ### end Alembic commands ###
