"""empty message

Revision ID: ed3704ce8630
Revises: f0135b06efdb
Create Date: 2020-11-20 03:02:48.353520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed3704ce8630'
down_revision = 'f0135b06efdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'genre', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'genre', type_='unique')
    # ### end Alembic commands ###
