"""empty message

Revision ID: 7dcb77285bf2
Revises: dbf5b598929c
Create Date: 2020-12-03 00:38:14.357743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dcb77285bf2'
down_revision = 'dbf5b598929c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('rank', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'rank')
    # ### end Alembic commands ###
